"""The graph engine contract.

Every backend implements this. The alpha ships ``NetworkXEngine`` (in-process,
runs and is tested everywhere). A ``Neo4jEngine`` can implement the same surface
later without touching discovery, since the graph is derived and rebuildable.
"""
from __future__ import annotations

from typing import Protocol


class GraphEngine(Protocol):
    def add_node(self, key: str, **attrs) -> None: ...
    def add_edge(self, src: str, dst: str, rel: str) -> None: ...
    def clear(self) -> None: ...
    def has_node(self, key: str) -> bool: ...
    def node(self, key: str) -> dict | None: ...
    def nodes(self) -> list[str]: ...
    def neighbors(self, key: str) -> list[str]: ...
    def neighbors_with_rel(self, key: str) -> list[tuple[str, str]]: ...
    def shortest_path(self, src: str, dst: str) -> list[str] | None: ...
    def betweenness(self) -> dict[str, float]: ...
